version: "3.3"

services:
  redis:
    image: redis
    container_name: broker
    restart: always

  backend:
    restart: on-failure
    container_name: backend
    build: backend
    ports:
      - "80:80"
    env_file:
      - backend/.env

  bot:
    restart: on-failure
    container_name: bot
    build: bot
    env_file:
      - bot/.env

